<?php

namespace Models;

use Monkey\Model;

/* AUTOGENERATED BY m_api_model.php */
class Configuration extends Model {
    protected $table="configuration";
	protected $primary_key="user_id";
	public $user_id;
	public $api_url;
	public $devices_key;
	public $devices_name;
	public $devices_value;
}