<?php

namespace Models;

use Monkey\Model;

/* AUTOGENERATED BY m_api_model.php */
class HistoCapteurs extends Model {
    protected $table="histo_capteurs";
	protected $primary_key="id";
	public $id;
	public $temperature;
	public $date;
	public $nom;
}