<?php

namespace Models;

use Monkey\Model;

/* AUTOGENERATED BY m_api_model.php */
class Utilisateurs extends Model {
    protected $table="utilisateurs";
	protected $primary_key="id";
	public $id;
	public $login;
	public $pass;
}